"""Unified daily report generation flow."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from src.database.db_manager import DatabaseManager
from src.reporting.daily_report import DailyReportBuilder
from src.reporting.obsidian_export import ObsidianExporter
from src.risk.risk_checker import RiskChecker
from src.scoring.strategy_scorer import StrategyScorer


@dataclass
class ReportArtifacts:
    """Artifacts generated by report flow."""

    report_date: str
    report_markdown: str
    report_file: Path
    signal_count: int
    risk_level: str


class ReportGenerator:
    """Coordinate scoring, risk-checking, report building and export."""

    def __init__(self, db: DatabaseManager, project_root: Path) -> None:
        self.db = db
        self.project_root = project_root
        self.scorer = StrategyScorer(db)
        self.risk_checker = RiskChecker(db)
        self.builder = DailyReportBuilder(db)
        self.exporter = ObsidianExporter(project_root)

    def generate(self, report_date: str | None = None, top_n: int = 5) -> ReportArtifacts:
        """Generate full daily report and export to Obsidian."""
        report_date = report_date or datetime.now().strftime("%Y-%m-%d")

        scores = self.scorer.score_all(trade_date=report_date, top_n=max(top_n, 5))
        risk_result = self.risk_checker.run()

        scores.short_term = self.risk_checker.apply_risk_to_candidates(scores.short_term, risk_result.alerts)
        scores.swing = self.risk_checker.apply_risk_to_candidates(scores.swing, risk_result.alerts)
        scores.stable = self.risk_checker.apply_risk_to_candidates(scores.stable, risk_result.alerts)

        signal_count = self.scorer.write_daily_signals(scores, trade_date=report_date)
        md = self.builder.build(report_date=report_date, scores=scores, risk_result=risk_result)
        report_file = self.exporter.export(report_date=report_date, markdown=md)

        return ReportArtifacts(
            report_date=report_date,
            report_markdown=md,
            report_file=report_file,
            signal_count=signal_count,
            risk_level=risk_result.level,
        )
